NAMED_METRICS_50 = [
    "monthly_revenue",
    "annual_recurring_revenue",
    "lifetime_value_ltv",
    "gross_margin_percent",
    "operating_margin_percent",
    "burn_rate",
    "runway_months",
    "cash_on_hand_million",
    "debt_ratio",
    "financing_round_count",

    "monthly_active_users",
    "daily_active_users",
    "user_growth_rate",
    "churn_rate",
    "churn_cohort_6mo",
    "activation_rate",
    "conversion_rate",
    "repeat_purchase_rate",
    "referral_rate",
    "session_frequency",

    "product_maturity_score",
    "product_security_score",
    "technical_debt_score",
    "release_frequency",
    "api_integrations_count",
    "uptime_percent",
    "scalability_score",
    "esg_sustainability_score",
    "patent_count",
    "technical_innovation_score",

    "employee_count",
    "employee_turnover_rate",
    "founder_diversity_score",
    "management_satisfaction_score",
    "tech_talent_ratio",
    "founder_exits",
    "founder_domain_exp_yrs",
    "founder_network_reach",
    "board_experience_score",
    "hiring_velocity_score",

    "nps_score",
    "customer_acquisition_cost",
    "roi_on_ad_spend",
    "lead_conversion_percent",
    "organic_traffic_share",
    "channel_partner_count",
    "support_ticket_volume",
    "support_ticket_sla_percent",
    "investor_interest_score",
    "category_leadership_score",
    "feel_score"
]

DOMAIN_TYPES = ["fintech","biotech","saas","climate"]